package org.pjc.entities;

public enum GameObjectTypes {
	OBJECT_PINK_STAR,
	OBJECT_RED_STAR,
	OBJECT_YELLOW_STAR,
	OBJECT_BLUE_STAR,
	OBJECT_CONSTELLATION_AQUARIUS,
	OBJECT_CONSTELLATION_ARIES,
	OBJECT_CONSTELLATION_CANCER,
	OBJECT_CONSTELLATION_CAPRICORN,
	OBJECT_CONSTELLATION_GEMINI,
	OBJECT_CONSTELLATION_LEO,
	OBJECT_CONSTELLATION_LIBRA,
	OBJECT_CONSTELLATION_PISCES,
	OBJECT_CONSTELLATION_SAGITTARIUS,
	OBJECT_CONSTELLATION_SCORPIO,
	OBJECT_CONSTELLATION_TAURUS,
	OBJECT_CONSTELLATION_VIRGO,
	OBJECT_ASTEROID,
	OBJECT_PLANET_1,
	OBJECT_PLANET_2,
	OBJECT_PLANET_3,
	OBJECT_PLANET_4,
	OBJECT_PLANET_5,
	OBJECT_PLANET_6
}
